{% set name = "edrixs" %}
{% set version = "0.0.7" %}
{% set sha256 = "fce7c1543d61df156696533dd7abcb7782e410bfb91afe7ae77109735146d160" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win]


requirements:
  build:
    - arpack-mpi
    - libopenblas
    - openmpi
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - arpack-mpi
    - matplotlib
    - mpi4py
    - numpy
    - openblas
    - scipy
    - sympy

test:
  files:
    - example_2_AIM_XAS.py
  imports:
    - edrixs
  commands:
    - python example_2_AIM_XAS.py
    - mpiexec -n 2 python example_2_AIM_XAS.py

about:
  home: https://github.com/NSLS-II/edrixs
  license: BSD-3-Clause
  license_file: LICENSE
  summary: An open source toolkit for simulating RIXS spectra based on ED
