{% set name = "edrixs" %}
{% set version = "0.0.6" %}
{% set sha256 = "87f7a8a414fa733f27b1f728df268aad27402dc8e8a45b4d5bf5e4f7f1d5170e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - arpack-mpi
    - libopenblas
    - openmpi
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - arpack-mpi
    - matplotlib
    - mpi4py
    - numpy
    - scipy
    - sympy

test:
  imports:
    - edrixs

about:
  home: https://github.com/NSLS-II/edrixs
  license: BSD-3-Clause
  license_file: LICENSE
  summary: An open source toolkit for simulating RIXS spectra based on ED
